### ISSUE TITLE
DataStore_Containers Lua Errors

### ISSUE THREAD

**Issue by evilgodly** [Thaoky/DataStore_Containers#1]
Upon login i am getting quite a few different DataContainer errors. Not even doing anything.

10x ...rfaceDataStore_Containers/API/PlayerBank.lua:13: Cannot find a library instance of "LibBit64".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@DataStore_Containers/API/PlayerBank.lua"]:13: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBit64"."

10x DataStore_Containers/API/GuildBank.lua:15: Cannot find a library instance of "LibBit64".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@DataStore_Containers/API/GuildBank.lua"]:15: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBit64"."

10x DataStore_Containers/DataStore_Containers.lua:23: Cannot find a library instance of "LibBit64".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@DataStore_Containers/DataStore_Containers.lua"]:23: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBit64"."

**Comment by Thaoky** [comment]
Fixed in 11.0.002
